-- =================================================================
-- Issue Tracker - Test Data Seeding Script (SQL Server)
-- =================================================================
-- This schema mirrors the tables generated by Entity Framework Core
-- (see src/IssueTracker.API/Data/AppDbContext.cs).
--
-- Enums are persisted as integers by EF Core:
--   Users.Role      -> 0 = Admin, 1 = Tester, 2 = Developer
--   Issues.Status   -> 0 = Open, 1 = InProgress, 2 = Resolved, 3 = Closed
--   Issues.Priority -> 0 = Low,  1 = Medium,     2 = High,      3 = Critical
-- =================================================================

-- 1. Tables (as created by EF Core)
CREATE TABLE Users (
    Id           INT IDENTITY(1,1) PRIMARY KEY,
    Email        NVARCHAR(256) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Role         INT NOT NULL          -- 0 Admin, 1 Tester, 2 Developer
);

CREATE UNIQUE INDEX IX_Users_Email ON Users(Email);

CREATE TABLE Issues (
    Id          INT IDENTITY(1,1) PRIMARY KEY,
    Title       NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Status      INT NOT NULL,          -- 0 Open, 1 InProgress, 2 Resolved, 3 Closed
    Priority    INT NOT NULL,          -- 0 Low, 1 Medium, 2 High, 3 Critical
    AssigneeId  INT NULL,
    CreatedAt   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Issues_Users_AssigneeId FOREIGN KEY (AssigneeId)
        REFERENCES Users(Id) ON DELETE SET NULL
);

-- 2. Test users (passwords are BCrypt hashes at runtime; plain text shown here for clarity only)
INSERT INTO Users (Email, PasswordHash, Role) VALUES
('admin@issuetracker.com',     'hashed_password', 0),
('tester@issuetracker.com',    'hashed_password', 1),
('developer@issuetracker.com', 'hashed_password', 2);

-- 3. Test issues
INSERT INTO Issues (Title, Description, Status, Priority, AssigneeId) VALUES
('Login button overlaps on mobile',          'UI issue on screens < 400px',           0, 1, NULL),
('API returns 500 on delete with comments',  'Deleting an issue with comments fails',  1, 3, 3),
('Update dependencies to latest versions',   'Security patch',                         2, 2, 3),
('Typo in registration email',               'Change "wellcome" to "welcome"',         3, 0, 3),
('Add dark mode toggle',                     'Feature request from marketing',         0, 0, NULL);
